# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: CI

jobs:
  unittests:
    name: Unit tests

    strategy:
      matrix:
        osversion:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.osversion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.805' # SDK Version to use.
      - run: dotnet restore --packages ../packages
        working-directory: ./commercetools.Sdk
      - run: dotnet build --no-restore --source ../packages -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test --verbosity=normal Tests/commercetools.Sdk.Domain.Tests --no-build -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test --verbosity=normal Tests/commercetools.Sdk.HttpApi.Tests --no-build -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test --verbosity=normal Tests/commercetools.Sdk.Linq.Tests --no-build -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test --verbosity=normal Tests/commercetools.Sdk.Serialization.Tests --no-build -c Release
        working-directory: ./commercetools.Sdk

  integrationtests:
    name: Integration tests

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        container:
          - BuiltIn
          - SimpleInjector
    env:
      CTP_Container: ${{ matrix.container }}
      CTP_Client__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_Client__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_Client__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_Client__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClient__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClient__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClient__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClient__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClientWithSmallerScope__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClientWithSmallerScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClientWithSmallerScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClientWithSmallerScope__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClientWithAnonymousScope__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClientWithAnonymousScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClientWithAnonymousScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClientWithAnonymousScope__Scope: ${{ secrets.CTP_SCOPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.805' # SDK Version to use.
      - run: dotnet restore --packages ../packages
        working-directory: ./commercetools.Sdk
      - run: dotnet build --no-restore --source ../packages -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test IntegrationTests/commercetools.Sdk.IntegrationTests --no-build -c Release --verbosity normal
        if: github.event_name == 'push'
        working-directory: ./commercetools.Sdk
      - run: dotnet test IntegrationTests/commercetools.Sdk.IntegrationTests --no-build -c Release --verbosity normal
        if: github.event_name == 'pull_request'
        working-directory: ./commercetools.Sdk
        env:
          CTP_Client__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_Client__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_Client__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_Client__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClient__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClient__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClient__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClient__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClientWithSmallerScope__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClientWithSmallerScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClientWithSmallerScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClientWithSmallerScope__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClientWithAnonymousScope__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClientWithAnonymousScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClientWithAnonymousScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClientWithAnonymousScope__Scope: ${{ secrets.CTP_SCOPE_PR }}
  core3:
    name: Core3 tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - BuiltIn
          - SimpleInjector
    env:
      CTP_Container: ${{ matrix.container }}
      CTP_Client__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_Client__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_Client__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_Client__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClient__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClient__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClient__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClient__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClientWithSmallerScope__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClientWithSmallerScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClientWithSmallerScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClientWithSmallerScope__Scope: ${{ secrets.CTP_SCOPE }}
      CTP_TokenClientWithAnonymousScope__ClientId: ${{ secrets.CTP_CLIENT_ID }}
      CTP_TokenClientWithAnonymousScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_TokenClientWithAnonymousScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_TokenClientWithAnonymousScope__Scope: ${{ secrets.CTP_SCOPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100' # SDK Version to use.
      - run: dotnet restore IntegrationTests/commercetools.Sdk.Core3Tests/commercetools.Sdk.Core3Tests.csproj --packages ../packages
        working-directory: ./commercetools.Sdk
      - run: dotnet build IntegrationTests/commercetools.Sdk.Core3Tests/commercetools.Sdk.Core3Tests.csproj --no-restore --source ../packages -c Release
        working-directory: ./commercetools.Sdk
      - run: dotnet test IntegrationTests/commercetools.Sdk.Core3Tests/commercetools.Sdk.Core3Tests.csproj --no-build -c Release
        if: github.event_name == 'push'
        working-directory: ./commercetools.Sdk
      - run: dotnet test IntegrationTests/commercetools.Sdk.Core3Tests/commercetools.Sdk.Core3Tests.csproj --no-build -c Release
        if: github.event_name == 'pull_request'
        working-directory: ./commercetools.Sdk
        env:
          CTP_Client__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_Client__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_Client__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_Client__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClient__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClient__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClient__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClient__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClientWithSmallerScope__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClientWithSmallerScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClientWithSmallerScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClientWithSmallerScope__Scope: ${{ secrets.CTP_SCOPE_PR }}
          CTP_TokenClientWithAnonymousScope__ClientId: ${{ secrets.CTP_CLIENT_ID_PR }}
          CTP_TokenClientWithAnonymousScope__ClientSecret: ${{ secrets.CTP_CLIENT_SECRET_PR }}
          CTP_TokenClientWithAnonymousScope__ProjectKey: ${{ secrets.CTP_PROJECT_KEY_PR }}
          CTP_TokenClientWithAnonymousScope__Scope: ${{ secrets.CTP_SCOPE_PR }}
  artifacts:
    name: Create artifacts
    runs-on: ubuntu-latest
    needs: [unittests, integrationtests, core3]
    steps:
      - uses: actions/checkout@master
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.805'
          source-url: https://nuget.pkg.github.com/commercetools/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./patch_csproj.rb --version 1.0.0-alpha-${{ github.run_number }} --patch **/*.csproj
      - run: dotnet restore --packages ../packages
        working-directory: ./commercetools.Sdk
      - run: dotnet build --no-restore --source ../packages -c Release
        working-directory: ./commercetools.Sdk
      - name: Create the package
        run: dotnet pack -c Release  -o ../../pack/
        working-directory: ./commercetools.Sdk
      - uses: actions/upload-artifact@v2
        with:
          name: commercetools.Sdk.1.0.0-alpha-${{ github.run_number }}
          path: pack
#      - name: Publish the package to GPR
#        run: dotnet nuget push pack/*.nupkg
